### ISSUE TITLE
site goal does not work with maven 3.1

### ISSUE THREAD

**Issue by davidkarlsen** [github/maven-plugins#46]
[ERROR] Failed to execute goal com.github.github:site-maven-plugin:0.8:site (default) on project commons-transaction-spring: Execution default of goal com.github.github:site-maven-plugin:0.8:site failed: An API incompatibility was encountered while executing com.github.github:site-maven-plugin:0.8:site: java.lang.NoSuchMethodError: org.apache.maven.execution.MavenSession.getRepositorySession()Lorg/sonatype/aether/RepositorySystemSession;
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>com.github.github:site-maven-plugin:0.8
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/home/et2448/.m2/repository/com/github/github/site-maven-plugin/0.8/site-maven-plugin-0.8.jar
[ERROR] urls[1] = file:/home/et2448/.m2/repository/org/eclipse/mylyn/github/org.eclipse.egit.github.core/2.1.3/org.eclipse.egit.github.core-2.1.3.jar
[ERROR] urls[2] = file:/home/et2448/.m2/repository/com/google/code/gson/gson/2.2.2/gson-2.2.2.jar
[ERROR] urls[3] = file:/home/et2448/.m2/repository/com/github/github/github-maven-core/0.6/github-maven-core-0.6.jar
[ERROR] urls[4] = file:/home/et2448/.m2/repository/org/codehaus/plexus/plexus-utils/1.1/plexus-utils-1.1.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[project>com.davidkarlsen.commonstransaction.spring:commons-transaction-spring:1.0-SNAPSHOT, parent: ClassRealm[maven.api, parent: null]]]
[ERROR]

**Comment by Cantido** [comment]
This fix is still unpublished, would it be possible to release this?

**Comment by joschi** [comment]
@Cantido The plugin works for me with Maven 3.3.9. Are you sure you're using the latest version of the plugin?

**Comment by Cantido** [comment]
@joschi That must have been my issue, I've updated Maven and it's working now. Thank you!
